// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: menuRedis.proto

package menuRedis

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MealCreate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MealId  string `protobuf:"bytes,1,opt,name=meal_id,json=mealId,proto3" json:"meal_id,omitempty"`
	Quality int64  `protobuf:"varint,2,opt,name=quality,proto3" json:"quality,omitempty"`
}

func (x *MealCreate) Reset() {
	*x = MealCreate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_menuRedis_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MealCreate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MealCreate) ProtoMessage() {}

func (x *MealCreate) ProtoReflect() protoreflect.Message {
	mi := &file_menuRedis_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MealCreate.ProtoReflect.Descriptor instead.
func (*MealCreate) Descriptor() ([]byte, []int) {
	return file_menuRedis_proto_rawDescGZIP(), []int{0}
}

func (x *MealCreate) GetMealId() string {
	if x != nil {
		return x.MealId
	}
	return ""
}

func (x *MealCreate) GetQuality() int64 {
	if x != nil {
		return x.Quality
	}
	return 0
}

type Status struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status bool `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *Status) Reset() {
	*x = Status{}
	if protoimpl.UnsafeEnabled {
		mi := &file_menuRedis_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_menuRedis_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_menuRedis_proto_rawDescGZIP(), []int{1}
}

func (x *Status) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type MealDelete struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MealId string `protobuf:"bytes,1,opt,name=meal_id,json=mealId,proto3" json:"meal_id,omitempty"`
}

func (x *MealDelete) Reset() {
	*x = MealDelete{}
	if protoimpl.UnsafeEnabled {
		mi := &file_menuRedis_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MealDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MealDelete) ProtoMessage() {}

func (x *MealDelete) ProtoReflect() protoreflect.Message {
	mi := &file_menuRedis_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MealDelete.ProtoReflect.Descriptor instead.
func (*MealDelete) Descriptor() ([]byte, []int) {
	return file_menuRedis_proto_rawDescGZIP(), []int{2}
}

func (x *MealDelete) GetMealId() string {
	if x != nil {
		return x.MealId
	}
	return ""
}

type Void struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Void) Reset() {
	*x = Void{}
	if protoimpl.UnsafeEnabled {
		mi := &file_menuRedis_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Void) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Void) ProtoMessage() {}

func (x *Void) ProtoReflect() protoreflect.Message {
	mi := &file_menuRedis_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Void.ProtoReflect.Descriptor instead.
func (*Void) Descriptor() ([]byte, []int) {
	return file_menuRedis_proto_rawDescGZIP(), []int{3}
}

type Meals struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Meals []*MealCreate `protobuf:"bytes,1,rep,name=meals,proto3" json:"meals,omitempty"`
}

func (x *Meals) Reset() {
	*x = Meals{}
	if protoimpl.UnsafeEnabled {
		mi := &file_menuRedis_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Meals) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Meals) ProtoMessage() {}

func (x *Meals) ProtoReflect() protoreflect.Message {
	mi := &file_menuRedis_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Meals.ProtoReflect.Descriptor instead.
func (*Meals) Descriptor() ([]byte, []int) {
	return file_menuRedis_proto_rawDescGZIP(), []int{4}
}

func (x *Meals) GetMeals() []*MealCreate {
	if x != nil {
		return x.Meals
	}
	return nil
}

var File_menuRedis_proto protoreflect.FileDescriptor

var file_menuRedis_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6d, 0x65, 0x6e, 0x75, 0x52, 0x65, 0x64, 0x69, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x6d, 0x65, 0x6e, 0x75, 0x52, 0x65, 0x64, 0x69, 0x73, 0x22, 0x3f, 0x0a, 0x0a,
	0x6d, 0x65, 0x61, 0x6c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x6d, 0x65,
	0x61, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x61,
	0x6c, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x71, 0x75, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x71, 0x75, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x22, 0x20, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22,
	0x25, 0x0a, 0x0a, 0x6d, 0x65, 0x61, 0x6c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x17, 0x0a,
	0x07, 0x6d, 0x65, 0x61, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x6d, 0x65, 0x61, 0x6c, 0x49, 0x64, 0x22, 0x06, 0x0a, 0x04, 0x76, 0x6f, 0x69, 0x64, 0x22, 0x34,
	0x0a, 0x05, 0x6d, 0x65, 0x61, 0x6c, 0x73, 0x12, 0x2b, 0x0a, 0x05, 0x6d, 0x65, 0x61, 0x6c, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x65, 0x6e, 0x75, 0x52, 0x65, 0x64,
	0x69, 0x73, 0x2e, 0x6d, 0x65, 0x61, 0x6c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x05, 0x6d,
	0x65, 0x61, 0x6c, 0x73, 0x32, 0xdd, 0x01, 0x0a, 0x04, 0x4d, 0x65, 0x6e, 0x75, 0x12, 0x36, 0x0a,
	0x0a, 0x43, 0x72, 0x65, 0x74, 0x61, 0x65, 0x4d, 0x65, 0x61, 0x6c, 0x12, 0x15, 0x2e, 0x6d, 0x65,
	0x6e, 0x75, 0x52, 0x65, 0x64, 0x69, 0x73, 0x2e, 0x6d, 0x65, 0x61, 0x6c, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x1a, 0x11, 0x2e, 0x6d, 0x65, 0x6e, 0x75, 0x52, 0x65, 0x64, 0x69, 0x73, 0x2e, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x2d, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x61, 0x6c,
	0x73, 0x12, 0x0f, 0x2e, 0x6d, 0x65, 0x6e, 0x75, 0x52, 0x65, 0x64, 0x69, 0x73, 0x2e, 0x76, 0x6f,
	0x69, 0x64, 0x1a, 0x10, 0x2e, 0x6d, 0x65, 0x6e, 0x75, 0x52, 0x65, 0x64, 0x69, 0x73, 0x2e, 0x6d,
	0x65, 0x61, 0x6c, 0x73, 0x12, 0x36, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65,
	0x61, 0x6c, 0x12, 0x15, 0x2e, 0x6d, 0x65, 0x6e, 0x75, 0x52, 0x65, 0x64, 0x69, 0x73, 0x2e, 0x6d,
	0x65, 0x61, 0x6c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x1a, 0x11, 0x2e, 0x6d, 0x65, 0x6e, 0x75,
	0x52, 0x65, 0x64, 0x69, 0x73, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x36, 0x0a, 0x0a,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x65, 0x61, 0x6c, 0x12, 0x15, 0x2e, 0x6d, 0x65, 0x6e,
	0x75, 0x52, 0x65, 0x64, 0x69, 0x73, 0x2e, 0x6d, 0x65, 0x61, 0x6c, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x1a, 0x11, 0x2e, 0x6d, 0x65, 0x6e, 0x75, 0x52, 0x65, 0x64, 0x69, 0x73, 0x2e, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x42, 0x14, 0x5a, 0x12, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x6d, 0x65, 0x6e, 0x75, 0x52, 0x65, 0x64, 0x69, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_menuRedis_proto_rawDescOnce sync.Once
	file_menuRedis_proto_rawDescData = file_menuRedis_proto_rawDesc
)

func file_menuRedis_proto_rawDescGZIP() []byte {
	file_menuRedis_proto_rawDescOnce.Do(func() {
		file_menuRedis_proto_rawDescData = protoimpl.X.CompressGZIP(file_menuRedis_proto_rawDescData)
	})
	return file_menuRedis_proto_rawDescData
}

var file_menuRedis_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_menuRedis_proto_goTypes = []any{
	(*MealCreate)(nil), // 0: menuRedis.mealCreate
	(*Status)(nil),     // 1: menuRedis.status
	(*MealDelete)(nil), // 2: menuRedis.mealDelete
	(*Void)(nil),       // 3: menuRedis.void
	(*Meals)(nil),      // 4: menuRedis.meals
}
var file_menuRedis_proto_depIdxs = []int32{
	0, // 0: menuRedis.meals.meals:type_name -> menuRedis.mealCreate
	0, // 1: menuRedis.Menu.CretaeMeal:input_type -> menuRedis.mealCreate
	3, // 2: menuRedis.Menu.GetMeals:input_type -> menuRedis.void
	0, // 3: menuRedis.Menu.UpdateMeal:input_type -> menuRedis.mealCreate
	2, // 4: menuRedis.Menu.DeleteMeal:input_type -> menuRedis.mealDelete
	1, // 5: menuRedis.Menu.CretaeMeal:output_type -> menuRedis.status
	4, // 6: menuRedis.Menu.GetMeals:output_type -> menuRedis.meals
	1, // 7: menuRedis.Menu.UpdateMeal:output_type -> menuRedis.status
	1, // 8: menuRedis.Menu.DeleteMeal:output_type -> menuRedis.status
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_menuRedis_proto_init() }
func file_menuRedis_proto_init() {
	if File_menuRedis_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_menuRedis_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*MealCreate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_menuRedis_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Status); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_menuRedis_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*MealDelete); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_menuRedis_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*Void); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_menuRedis_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*Meals); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_menuRedis_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_menuRedis_proto_goTypes,
		DependencyIndexes: file_menuRedis_proto_depIdxs,
		MessageInfos:      file_menuRedis_proto_msgTypes,
	}.Build()
	File_menuRedis_proto = out.File
	file_menuRedis_proto_rawDesc = nil
	file_menuRedis_proto_goTypes = nil
	file_menuRedis_proto_depIdxs = nil
}
